import Foundation
import simd

/// PLY point cloud exporter - extract_floorplan.py compatible
class PLYExporter {

    /// Export scan data as ASCII PLY file
    static func export(
        featurePoints: [ScanPoint],
        meshPoints: [SIMD3<Float>],
        filename: String
    ) -> URL? {
        let totalCount = featurePoints.count + meshPoints.count
        guard totalCount > 0 else { return nil }

        // Build PLY content
        var lines: [String] = []
        lines.reserveCapacity(totalCount + 10)

        // Header
        lines.append("ply")
        lines.append("format ascii 1.0")
        lines.append("comment Generated by MoveViz iOS App")
        lines.append("comment Compatible with extract_floorplan.py")
        lines.append("element vertex \(totalCount)")
        lines.append("property float x")
        lines.append("property float y")
        lines.append("property float z")
        lines.append("property uchar red")
        lines.append("property uchar green")
        lines.append("property uchar blue")
        lines.append("end_header")

        // Feature points (with color)
        for p in featurePoints {
            lines.append(String(
                format: "%.6f %.6f %.6f %d %d %d",
                p.position.x, p.position.y, p.position.z,
                p.color.x, p.color.y, p.color.z
            ))
        }

        // Mesh points (gray)
        for v in meshPoints {
            lines.append(String(
                format: "%.6f %.6f %.6f 160 160 160",
                v.x, v.y, v.z
            ))
        }

        let content = lines.joined(separator: "\n") + "\n"

        // Save to temp directory
        let tempDir = FileManager.default.temporaryDirectory
        let timestamp = Int(Date().timeIntervalSince1970)
        let fileURL = tempDir.appendingPathComponent("\(filename)_\(timestamp).ply")

        do {
            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            print("PLY export failed: \(error)")
            return nil
        }
    }

    /// Export in COLMAP points3D.txt format (alternative export)
    static func exportCOLMAP(
        featurePoints: [ScanPoint],
        meshPoints: [SIMD3<Float>],
        filename: String
    ) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let dirURL = tempDir.appendingPathComponent("\(filename)_colmap")

        do {
            try FileManager.default.createDirectory(at: dirURL, withIntermediateDirectories: true)
        } catch {
            return nil
        }

        var lines: [String] = []
        lines.append("# 3D point list with one line of data per point:")
        lines.append("#   POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)")
        let totalCount = featurePoints.count + meshPoints.count
        lines.append("# Number of points: \(totalCount), mean track length: 0")

        var pointID: Int = 1

        for p in featurePoints {
            lines.append(String(
                format: "%d %.6f %.6f %.6f %d %d %d 0.0",
                pointID, p.position.x, p.position.y, p.position.z,
                p.color.x, p.color.y, p.color.z
            ))
            pointID += 1
        }

        for v in meshPoints {
            lines.append(String(
                format: "%d %.6f %.6f %.6f 160 160 160 0.0",
                pointID, v.x, v.y, v.z
            ))
            pointID += 1
        }

        let content = lines.joined(separator: "\n") + "\n"
        let fileURL = dirURL.appendingPathComponent("points3D.txt")

        do {
            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            return nil
        }
    }
}
